### ISSUE TITLE
Error running script.lua:  bad argument #1 to 'dir' (string expected, got nil)

### ISSUE THREAD

**Issue by NataliaDiaz** [TLESORT/Learning-State-Representation#1]
Probably some local path error?

Learning-State-Representation$ th script.lua
Test actuel : ./Log/19-10/Everything/	
true	
true	
true	
true	
/home/natalia/torch/install/bin/luajit: /home/natalia/torch/install/share/lua/5.1/paths/init.lua:26: bad argument #1 to 'dir' (string expected, got nil)
stack traceback:
	[C]: in function 'dir'
	/home/natalia/torch/install/share/lua/5.1/paths/init.lua:26: in function 'files'
	./Get_Images_Set.lua:9: in function 'images_Paths'
	script.lua:91: in function 'train_Epoch'
	script.lua:273: in main chunk
	[C]: in function 'dofile'
	...alia/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670

Also, regarding function naming:
1. What is supposed to do have-TODO() method?
2. Should the method doStuff_* [temp, caus, etc.) be called something more intuitive?, e.g. perhaps backpropagate() or getLossAndGradient()?

**Comment by NataliaDiaz** [comment]
Similar error when running: 
 /Supervise$ th script_supervised.lua 
Test actuel : ./Log/21-10/	
/home/natalia/torch/install/bin/luajit: /home/natalia/torch/install/share/lua/5.1/paths/init.lua:26: bad argument #1 to 'dir' (string expected, got nil)
stack traceback:
	[C]: in function 'dir'
	/home/natalia/torch/install/share/lua/5.1/paths/init.lua:26: in function 'files'
	...a/dream/Learning-State-Representation/Get_Images_Set.lua:9: in function 'images_Paths'
	script_supervised.lua:120: in function 'train_Epoch'
	script_supervised.lua:198: in main chunk
	[C]: in function 'dofile'
	...alia/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670



And when running:
th load_modele.lua 
/home/natalia/torch/install/bin/luajit: cannot open </home/timothee/git/Learning_State_Representation/Supervise/Log/18-10/Save18-10.t7> in mode r  at /home/natalia/torch/pkg/torch/lib/TH/THDiskFile.c:670

Is it possible to save the model to a local /models/ folder?

**Comment by TLESORT** [comment]
The data foder have to be named "data_baxter" and containing image from the drive folder, I hope it will solve your problem for supervised and unsupervised.

Concerning name of "dostuff" function I think something like "apply[Prop,Caus,Temp,Rep]Criterion" coud be more appropriate. What to you think?

I am sorry for the names of my functions it's a shame ..... :)

Have_Todo is a function which determines if a priors is applied during training. It return true if yes and no otherwise

The function "save_model" in script save models for each test done. The tests done are define in the list "Tests_Todo". Each test train the model with a particular combination of priors but I think the only to keep is the one with all the priors.
Once you have done a training you can use the trained model for load_modele.lua using the variable "name" at line 128. (It is not very user friendly for instance... :s ).

**Comment by NataliaDiaz** [comment]
Ok I have it now in the main folder, but still Path is null when running:

```~/dream/baxter_representation_learning_3D/Supervise$ th script_supervised.lua 
Path data_baxter including record, excluding uyfouhjbhytfoughl, list 0	
Test actuel : ./Log/21-10/	
list_folders_images size: 0	
/home/natalia/torch/install/bin/luajit: script_supervised.lua:121: attempt to concatenate a nil value
stack traceback:
	script_supervised.lua:121: in function 'train_Epoch'
	script_supervised.lua:201: in main chunk
	[C]: in function 'dofile'
	...alia/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
```


seems like data is not read properly?
because when I do:
```
print('list_folders_images size: '..#list_folders_images)
print('list_folders_images[4]: '..list_folders_images[indice_test])
```
and 
```
print ('Path '..Path..' including '..incl..', excluding '..excl..', list of size: '.. #list)
```
in Get_Images_Set.lua , in  getFolders():
```
natalia@nataliaHPProDesk:~/dream/baxter_representation_learning_3D/Supervise$ th script_supervised.lua 
Path data_baxter including record, excluding uyfouhjbhytfoughl, list 0	
Test actuel : ./Log/21-10/	
/home/natalia/torch/install/bin/luajit: ...eam/baxter_representation_learning_3D/Get_Images_Set.lua:10: attempt to concatenate local 'Path' (a nil value)
stack traceback:
	...eam/baxter_representation_learning_3D/Get_Images_Set.lua:10: in function 'images_Paths'
	script_supervised.lua:123: in function 'train_Epoch'
	script_supervised.lua:201: in main chunk
	[C]: in function 'dofile'
	...alia/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
natalia@nataliaHPProDesk:~/dream/baxter_representation_learning_3D/Supervise$ th script_supervised.lua 
```


And the same running script.lua. 

Also, what the names of the models mean? FM?
./models/topTripleFM_Split.lua
topUniqueFM_Deeper2.lua

**Comment by TLESORT** [comment]
Does the code for loading images works with the script "script.lua" inside project repository?

***********************************
When running the supervised script, if you change : 
local Path="data_baxter"
to
local Path="../data_baxter"

in the function Get_HeadCamera_View_Files()  in file Get_Images_Set.lua

Does it works?

if not, can you send me the output of the command : "ls -R  | grep -v .jpg" executed inside your project repository?
***********************************
FM means feature map. I tried two models, one with one feature map for each dimension learned ("topTripleFM_Split.lua") and another with a shared top feature map for the three dimensions ("topUniqueFM_Deeper2.lua")

**Comment by NataliaDiaz** [comment]
This is the result of such command (after updating the path to the father directory where data is):
<details>
/baxter_representation_learning_3D$ ls -R | grep -v .jpg
.:
data_baxter
evaluateRepresentation3D.lua
functions.lua
Get_Images_Set.lua
Log
models
MSDC.lua
printing.lua
priors.lua
README.md
script.lua
ssh_key_natalia_zeus
ssh_key_natalia_zeus.pub
Supervised
testRepresentation3D.lua
weight-init.lua

./data_baxter:
record_11
record_8
too big for cpu

./data_baxter/record_11:
recorded_button1_is_pressed.txt
recorded_button1_position.txt
recorded_button1_position.txt~
recorded_cameras_head_camera_2_image_compressed
recorded_robot_joint_states.txt
recorded_robot_limb_left_endpoint_action.txt
recorded_robot_limb_left_endpoint_state.txt

./data_baxter/record_11/recorded_cameras_head_camera_2_image_compressed:
time.txt

./data_baxter/record_8:
recorded_button1_is_pressed.txt
recorded_button1_position.txt
recorded_cameras_head_camera_2_image_compressed
recorded_robot_joint_states.txt
recorded_robot_limb_left_endpoint_action.txt
recorded_robot_limb_left_endpoint_state.txt

./data_baxter/record_8/recorded_cameras_head_camera_2_image_compressed:
time.txt

./data_baxter/too big for cpu:
Data_Baxter_sup
record_0
record_1
record_10
record_11_long
record_2
record_3
record_4
record_5
record_6
record_7
record_9

./data_baxter/too big for cpu/Data_Baxter_sup:
record_11
record_8

./data_baxter/too big for cpu/Data_Baxter_sup/record_11:
recorded_button1_is_pressed.txt
recorded_button1_position.txt
recorded_button1_position.txt~
recorded_cameras_head_camera_2_image_compressed
recorded_robot_joint_states.txt
recorded_robot_limb_left_endpoint_action.txt
recorded_robot_limb_left_endpoint_state.txt

./data_baxter/too big for cpu/Data_Baxter_sup/record_11/recorded_cameras_head_camera_2_image_compressed:
time.txt

./data_baxter/too big for cpu/Data_Baxter_sup/record_8:
recorded_button1_is_pressed.txt
recorded_button1_position.txt
recorded_cameras_head_camera_2_image_compressed
recorded_robot_joint_states.txt
recorded_robot_limb_left_endpoint_action.txt
recorded_robot_limb_left_endpoint_state.txt

./data_baxter/too big for cpu/Data_Baxter_sup/record_8/recorded_cameras_head_camera_2_image_compressed:
time.txt

./data_baxter/too big for cpu/record_0:
recorded_button1_is_pressed.txt
recorded_button1_position.txt
recorded_cameras_head_camera_2_image_compressed
recorded_robot_joint_states.txt
recorded_robot_limb_left_endpoint_action.txt
recorded_robot_limb_left_endpoint_state.txt

./data_baxter/too big for cpu/record_0/recorded_cameras_head_camera_2_image_compressed:
time.txt

./data_baxter/too big for cpu/record_1:
recorded_button1_is_pressed.txt
recorded_button1_position.txt
recorded_cameras_head_camera_2_image_compressed
recorded_robot_joint_states.txt
recorded_robot_limb_left_endpoint_action.txt
recorded_robot_limb_left_endpoint_state.txt

./data_baxter/too big for cpu/record_1/recorded_cameras_head_camera_2_image_compressed:
time.txt

./data_baxter/too big for cpu/record_10:
recorded_button1_is_pressed.txt
recorded_button1_is_pressed.txt~
recorded_button1_position.txt
recorded_cameras_head_camera_2_image_compressed
recorded_robot_joint_states.txt
recorded_robot_limb_left_endpoint_action.txt
recorded_robot_limb_left_endpoint_action.txt~
recorded_robot_limb_left_endpoint_state.txt

./data_baxter/too big for cpu/record_10/recorded_cameras_head_camera_2_image_compressed:
time.txt

./data_baxter/too big for cpu/record_11_long:
recorded_button1_is_pressed.txt
recorded_button1_is_pressed.txt~
recorded_button1_position.txt
recorded_cameras_head_camera_2_image_compressed
recorded_robot_joint_states.txt
recorded_robot_limb_left_endpoint_action.txt
recorded_robot_limb_left_endpoint_state.txt

./data_baxter/too big for cpu/record_11_long/recorded_cameras_head_camera_2_image_compressed:
time.txt

./data_baxter/too big for cpu/record_2:
recorded_button1_is_pressed.txt
recorded_button1_position.txt
recorded_cameras_head_camera_2_image_compressed
recorded_robot_joint_states.txt
recorded_robot_limb_left_endpoint_action.txt
recorded_robot_limb_left_endpoint_state.txt

./data_baxter/too big for cpu/record_2/recorded_cameras_head_camera_2_image_compressed:
time.txt

./data_baxter/too big for cpu/record_3:
recorded_button1_is_pressed.txt
recorded_button1_position.txt
recorded_cameras_head_camera_2_image_compressed
recorded_robot_joint_states.txt
recorded_robot_limb_left_endpoint_action.txt
recorded_robot_limb_left_endpoint_state.txt

./data_baxter/too big for cpu/record_3/recorded_cameras_head_camera_2_image_compressed:
time.txt

./data_baxter/too big for cpu/record_4:
recorded_button1_is_pressed.txt
recorded_button1_position.txt
recorded_cameras_head_camera_2_image_compressed
recorded_robot_joint_states.txt
recorded_robot_limb_left_endpoint_action.txt
recorded_robot_limb_left_endpoint_state.txt

./data_baxter/too big for cpu/record_4/recorded_cameras_head_camera_2_image_compressed:
time.txt

./data_baxter/too big for cpu/record_5:
recorded_button1_is_pressed.txt
recorded_button1_position.txt
recorded_cameras_head_camera_2_image_compressed
recorded_robot_joint_states.txt
recorded_robot_limb_left_endpoint_action.txt
recorded_robot_limb_left_endpoint_state.txt

./data_baxter/too big for cpu/record_5/recorded_cameras_head_camera_2_image_compressed:
time.txt

./data_baxter/too big for cpu/record_6:
recorded_button1_is_pressed.txt
recorded_button1_position.txt
recorded_cameras_head_camera_2_image_compressed
recorded_robot_joint_states.txt
recorded_robot_limb_left_endpoint_action.txt
recorded_robot_limb_left_endpoint_state.txt

./data_baxter/too big for cpu/record_6/recorded_cameras_head_camera_2_image_compressed:
time.txt

./data_baxter/too big for cpu/record_7:
recorded_button1_is_pressed.txt
recorded_button1_position.txt
recorded_cameras_head_camera_2_image_compressed
recorded_robot_joint_states.txt
recorded_robot_limb_left_endpoint_action.txt
recorded_robot_limb_left_endpoint_state.txt

./data_baxter/too big for cpu/record_7/recorded_cameras_head_camera_2_image_compressed:
time.txt

./data_baxter/too big for cpu/record_9:
recorded_button1_is_pressed.txt
recorded_button1_position.txt
recorded_cameras_head_camera_2_image_compressed
recorded_robot_joint_states.txt
recorded_robot_limb_left_endpoint_action.txt
recorded_robot_limb_left_endpoint_state.txt

./data_baxter/too big for cpu/record_9/recorded_cameras_head_camera_2_image_compressed:
time.txt

./Log:
10-19

./Log/10-19:
Everything

./Log/10-19/Everything:
The_Truth.Log
The_Truth.Log.eps

./models:
minimalNetModel.lua
topTripleFM_Split.lua
topUniqueFM_Deeper2.lua

./Supervised:
script_supervised.lua
weight-init.lua
</details>


with  error:
`
~/dream/baxter_representation_learning_3D/Supervised$ th script_supervised.lua 
Test actuel : ./Log/21-10/	
/home/natalia/torch/install/bin/luajit: /home/natalia/torch/install/share/lua/5.1/paths/init.lua:26: bad argument #1 to 'dir' (string expected, got nil)
stack traceback:
	[C]: in function 'dir'
	/home/natalia/torch/install/share/lua/5.1/paths/init.lua:26: in function 'files'
	...eam/baxter_representation_learning_3D/Get_Images_Set.lua:10: in function 'images_Paths'
	script_supervised.lua:144: in function 'train_Epoch'
	script_supervised.lua:224: in main chunk
	[C]: in function 'dofile'
	...alia/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670

`

**Comment by TLESORT** [comment]
Can you try to run the script with only record_* folders inside your data_baxter folder?
( without record_11_long)

ls command in data_baxter folder should give : 
'
record_0
record_1
record_10
record_2
record_3
record_4
record_5
record_6
record_7
record_9
'

**Comment by NataliaDiaz** [comment]
Supervised main script runs now! however for the regular script in main folder, I get the same error, I updated the cpu-flag optimized details in 
https://github.com/Mathieu-Seurin/baxter_representation_learning_3D
but there shouldn't be any  major change apart from those you told me.
Also uploaded the data to this private repo for practicality and to see we are using the same dataset: https://github.com/NataliaDiaz/baxter_data
what can be?

**Comment by NataliaDiaz** [comment]
I introduced a bug myself, so data path now works, I made it modular in a global variable setting now so that depending on the script being run, it is script-dependent the baxter_data location setting, instead of a local variable to GetImages_Set() funcion images_Paths.
All is in https://github.com/Mathieu-Seurin/baxter_representation_learning_3D
However, reducing the number of parts per batch processed to 50 again to avoid priors watchdog attacks (ie. not finding enough data for the prior to be fulfilled and we find frames where their condition is met), And now I get the CAUS Watchdog warning and consequent error:

`
baxter_representation_learning_3D$ th script.lua 
(...)
Mutual Info Référence	
2.787788119386	
Mutual Info	
1.5841707585125	
Figure saved!	
Saved at : ./Log/10-19/Everything/Save10-19.t7	
--------------Epoch : 2 ---------------	
Loaded images from Path: /home/natalia/dream/baxter_representation_learning_3D/baxter_data/record_2/recorded_cameras_head_camera_2_image_compressed	
Loaded images from Path: /home/natalia/dream/baxter_representation_learning_3D/baxter_data/record_2/recorded_cameras_head_camera_2_image_compressed	
CAUS WATCHDOG ATTACK!!!!!!!!!!!!!!!!!!	
/home/natalia/torch/install/bin/luajit: bad argument #3 to '?' (torch.*Tensor expected, got nil)
stack traceback:
	[C]: at 0x7f344e6b91c0
	[C]: in function '__newindex'
	...ia/dream/baxter_representation_learning_3D/functions.lua:192: in function 'getRandomBatchFromSeparateList'
	script.lua:46: in function 'Rico_Training'
	script.lua:187: in function 'train_Epoch'
	script.lua:319: in main chunk
	[C]: in function 'dofile'
	...alia/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
natalia@nataliaHPProDesk:~/dream/baxter_representation_learning_3D$ th load_model.lua 
/home/natalia/torch/install/bin/luajit: cannot open <./Supervised/Log/18-10/Save18-10.t7> in mode r  at /home/natalia/torch/pkg/torch/lib/TH/THDiskFile.c:670
stack traceback:
	[C]: at 0x7fe977974360
	[C]: in function 'DiskFile'
	/home/natalia/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
	load_model.lua:128: in main chunk
	[C]: in function 'dofile'
	...alia/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
`

Any hints to avoid it with baxter_data? (trying with newly fresh shorter sequences dataset now, but it probably makes it worse... (?))

**Comment by NataliaDiaz** [comment]
The path issue with a global variable Path which becomes nil is ilustrated while running train.th (modularized version of script.th), in line 10-11 of Get_images_Set.lua (method images_Paths(). I.e., passing the argumetn Path does not seem taking effect:

And the second error is the one also demosntrated below: error list are not same lenght
stack traceback:
	[C]: in function 'assert'
	...lia/dream/baxter_representation_learning_3D/printing.lua:204: in function 'show_figure'
<details>
/baxter_representation_learning_3D$ th train.lua 
Running main script with useCUDA flag: false	
Running main script with useSecondGPU flag: false	
nb_parts per batch: 50 LearningRate: 0.001 Using data folder: ./baxter_data	
Get_HeadCamera_View_Files(Path: ./baxter_data	
list_folders_images=	
{
  1 : "/home/natalia/dream/baxter_representation_learning_3D/baxter_data/record_0/recorded_cameras_head_camera_2_image_compressed"
  2 : "/home/natalia/dream/baxter_representation_learning_3D/baxter_data/record_1/recorded_cameras_head_camera_2_image_compressed"
  3 : "/home/natalia/dream/baxter_representation_learning_3D/baxter_data/record_10/recorded_cameras_head_camera_2_image_compressed"
  4 : "/home/natalia/dream/baxter_representation_learning_3D/baxter_data/record_2/recorded_cameras_head_camera_2_image_compressed"
  5 : "/home/natalia/dream/baxter_representation_learning_3D/baxter_data/record_3/recorded_cameras_head_camera_2_image_compressed"
  6 : "/home/natalia/dream/baxter_representation_learning_3D/baxter_data/record_4/recorded_cameras_head_camera_2_image_compressed"
  7 : "/home/natalia/dream/baxter_representation_learning_3D/baxter_data/record_5/recorded_cameras_head_camera_2_image_compressed"
  8 : "/home/natalia/dream/baxter_representation_learning_3D/baxter_data/record_6/recorded_cameras_head_camera_2_image_compressed"
  9 : "/home/natalia/dream/baxter_representation_learning_3D/baxter_data/record_7/recorded_cameras_head_camera_2_image_compressed"
  10 : "/home/natalia/dream/baxter_representation_learning_3D/baxter_data/record_9/recorded_cameras_head_camera_2_image_compressed"
}
Running test: 1	. Saving in Log_Folder: ./Log/10-19/Everything/...	
Which priors are being applied?:	
true	
true	
true	
true	
images Path variable suddenly becomes nil here if not reset!: ( WHY?!)	
./baxter_data	
Loaded images from Path: ./baxter_data	
Plotting the truth... 	
/home/natalia/torch/install/bin/luajit: ...lia/dream/baxter_representation_learning_3D/printing.lua:204: error list are not same lenght
stack traceback:
	[C]: in function 'assert'
	...lia/dream/baxter_representation_learning_3D/printing.lua:204: in function 'show_figure'
	train.lua:132: in function 'train_Epoch'
	train.lua:314: in main chunk
	[C]: in function 'dofile'
	...alia/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
<\details>

**Comment by NataliaDiaz** [comment]
Still keep getting the original error running in this original repo script.th with only records 0-10 without record 11 and the other one. Are you still able to run it?
`
Learning-State-Representation$ th script.lua 
Test actuel : ./Log/19-10/Everything/	
true	
true	
true	
true	
/home/gpu_center/torch/install/bin/luajit: /home/gpu_center/torch/install/share/lua/5.1/paths/init.lua:26: bad argument #1 to 'dir' (string expected, got nil)
stack traceback:
	[C]: in function 'dir'
	/home/gpu_center/torch/install/share/lua/5.1/paths/init.lua:26: in function 'files'
	./Get_Images_Set.lua:9: in function 'images_Paths'
	script.lua:91: in function 'train_Epoch'
	script.lua:274: in main chunk
	[C]: in function 'dofile'
	...nter/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
gpu_center@timothee-ThinkStation-P700:~/Learning-State-Representation$ 

`

**Comment by NataliaDiaz** [comment]
Solved,
this commit explains the data path issue, which was wrong:
https://github.com/NataliaDiaz/data_baxter/commit/bd86343f06d762252a7d1bcc8b1a1602800f247b
and all data is consistent with same naming here: 
https://github.com/NataliaDiaz

**Comment by TLESORT** [comment]
Ok cool :) :+1:
