### ISSUE TITLE
Can parameter Diameter be removed?

### ISSUE THREAD

**Issue by NataliaDiaz** [TLESORT/Learning-State-Representation#3]
Seems like the model
https://github.com/TLESORT/Learning-State-Representation/blob/master/models/topTripleFM_Split.lua
is only made for 1D representation learning?

**Comment by TLESORT** [comment]
I think you means parameter "Dimension" :)
Yes, it can be removed it is useless, I will do it
The model is only made for 3D dimension, the output is mean to be the concatenation of three 1D output.

**Comment by NataliaDiaz** [comment]
yes sorry :) thanks
